export const menuItems = [
  {
    id: 1,
    name: "Margherita Pizza",
    price: 7.99,
    img: "/images/pizza-margherita.png",
    description: "Classic cheese & tomato with fresh basil.",
    category: "Pizza",
  },
  {
    id: 2,
    name: "Pepperoni Pizza",
    price: 9.49,
    img: "/images/pizza-pepperoni.png",
    description: "Loaded with spicy pepperoni & mozzarella.",
    category: "Pizza",
  },
  {
    id: 3,
    name: "BBQ Chicken Pizza",
    price: 10.99,
    img: "/images/pizza-bbq.png",
    description: "Tangy BBQ sauce with grilled chicken & onions.",
    category: "Pizza",
  },
  {
    id: 4,
    name: "Classic Beef Burger",
    price: 6.49,
    img: "/images/burger-classic.png",
    description: "Juicy beef patty with lettuce, tomato & cheese.",
    category: "Burger",
  },
  {
    id: 5,
    name: "Chicken Zinger Burger",
    price: 6.99,
    img: "/images/burger-zinger.png",
    description: "Crispy fried chicken fillet with mayo & lettuce.",
    category: "Burger",
  },
  {
    id: 6,
    name: "French Fries",
    price: 3.49,
    img: "/images/fries.png",
    description: "Golden, crispy & lightly salted.",
    category: "Sides",
  },
  {
    id: 7,
    name: "Cheese Loaded Fries",
    price: 4.49,
    img: "/images/cheese-fries.png",
    description: "Topped with gooey melted cheese & herbs.",
    category: "Sides",
  },
  {
    id: 8,
    name: "Coca-Cola (500ml)",
    price: 1.99,
    img: "/images/coke.png",
    description: "Classic refreshment, served chilled.",
    category: "Drinks",
  },
  {
    id: 9,
    name: "Orange Juice",
    price: 2.49,
    img: "/images/orange-juice.png",
    description: "Freshly squeezed, no added sugar.",
    category: "Drinks",
  },
  {
    id: 10,
    name: "Chocolate Lava Cake",
    price: 4.99,
    img: "/images/lava-cake.png",
    description: "Warm chocolate cake with gooey center.",
    category: "Dessert",
  },
];
